name: "build-external"
description: "Either builds an external dependency or fetches it from cache"

inputs:
  library:
    description: "Name of the dependency to build"
    required: true
  version:
    description: "Version of the dependency to build"
    required: true
  host-build:
    description: "Whether to build a host library for use in cross-compiling (e.g. a Linux build of Qt that gets used during the WASM build process)"
    required: false
    default: false

outputs:
  path:
    description: "Absolute path to the installed dependency"
    value: ${{ github.workspace }}/${{ steps.lib-build-dir.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Determine the build directory
      id: lib-build-dir
      shell: bash
      run: |
        echo "path=build/external${{ inputs.host-build == 'true' && '/host' || '' }}/${{ inputs.library }}-${{ inputs.version }}" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: cache-check
      with:
        path: ${{ steps.lib-build-dir.outputs.path }}
        key: ${{ inputs.library }}-${{ inputs.version }}-${{ runner.os }}-${{ matrix.build-output }}${{ inputs.host-build == 'true' && '-host' || '' }}

    - name: Build library
      if: steps.cache-check.outputs.cache-hit != 'true'
      # The Windows Qt build fails if we try to use bash, since it shells out to
      # cmd and doesn't protect the path backslashes from bash
      shell: ${{ runner.os == 'windows' && 'cmd' || 'bash' }}
      env:
        use-emsdk: ${{ matrix.build-output == 'wasm' && inputs.host-build == 'false' && 'true' }}
        endl: ${{ runner.os == 'windows' && '^' || '\' }}
      run: |
        ${{ env.use-emsdk == 'true' && 'source emsdk_env.sh && ' || '' }}${{env.endl}}
        cmake --build ${{ steps.lib-build-dir.outputs.path }} --verbose${{env.endl}}
              --target ${{ inputs.library }}${{env.endl}}
              --config ${{ env.BUILD_TYPE }}