name: 2025-4 Nightly Build

env:
  BRANCH: main

on:
  schedule:
    - cron: '7 2 * * *'  # Avoid demand peaks at minute 0
  workflow_dispatch: ~

jobs:
  increment-version:
    runs-on: ubuntu-latest
    outputs:
      has_recent_commits: ${{ steps.check-commits.outputs.has_recent_commits }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for recent commits
        id: check-commits
        run: |
          git fetch origin ${{ env.BRANCH }}
          has_recent=$(git log origin/${{ env.BRANCH }} --since="24 hours ago" --not --author="GitHub Action" --oneline | head -1 | wc -l)
          echo "has_recent_commits=$([ $has_recent -gt 0 ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Increment patch version
        if: steps.check-commits.outputs.has_recent_commits == 'true'
        run: |
          current_version=$(grep "VERSION " CMakeLists.txt | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          new_version=$(echo $current_version | awk -F. '{print $1"."$2"."($3+1)}')
          sed -i "s/VERSION $current_version/VERSION $new_version/" CMakeLists.txt
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Create PR for version increment
        if: steps.check-commits.outputs.has_recent_commits == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch_name="version-increment-${{ env.NEW_VERSION }}"
          git checkout -b "$branch_name"
          git add CMakeLists.txt
          git commit -m "Increment patch version to ${{ env.NEW_VERSION }}"
          git push origin "$branch_name"
          gh pr create \
            --title "Increment patch version to ${{ env.NEW_VERSION }}" \
            --body "Automated nightly version increment" \
            --head "$branch_name" \
            --base "${{ env.BRANCH }}"
          gh pr merge --auto --merge

  build-and-test:
    needs: increment-version
    if: needs.increment-version.outputs.has_recent_commits == 'true'
    uses: ./.github/workflows/sketcher-builder.yml
